/*
 * fonts.h - LVGL v8 bitmap fonts (4bpp) generated for the miner's original
 * 3 pilot screens (19-zen, 01-painel, 14-hashrate). Generated by
 * tools/fonts/generate-fonts.ps1 from OFL TTFs from Google Fonts - see
 * tools/fonts/README.md to reproduce them.
 *
 * DO NOT HAND-EDIT: any .c file in this folder is regenerated from scratch
 * by running the pipeline in tools/fonts/. To change weight/size/glyph set,
 * change generate-fonts.ps1 and run it again, never edit the generated .c
 * file directly.
 */
#ifndef NQPP_DISPLAYS_FONTS_H
#define NQPP_DISPLAYS_FONTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/* 19-zen: hashrate hero number (digits + comma/dot/hyphen/%/deg only) */
extern const lv_font_t font_instrument_serif_hero; /* Instrument Serif Regular, 188 px */

/* 01-painel: PFD-style instrument tapes + hashrate hero */
extern const lv_font_t font_saira_condensed_bold_108; /* Saira Condensed Bold, 108 px - hashrate hero */
extern const lv_font_t font_saira_condensed_bold_28; /* Saira Condensed Bold, 28 px - tape center reading */
extern const lv_font_t font_saira_condensed_semibold_24; /* Saira Condensed SemiBold, 24 px - footer (includes governor state words) */
extern const lv_font_t font_saira_condensed_semibold_15; /* Saira Condensed SemiBold, 15 px - tape tick marks/numeric labels */

/* Archivo: general text (units, titles, axes, labels) across the 3 screens */
extern const lv_font_t font_archivo_regular_15; /* Archivo Regular (wdth 88%), 15 px - small labels (zen footer, painel titles/unit/footer) */
extern const lv_font_t font_archivo_regular_19; /* Archivo Regular (wdth 88%), 19 px - hero unit in 19-zen */
extern const lv_font_t font_archivo_medium_15; /* Archivo Medium (wdth 82%), 15 px - tabs/axis/average labels in 14-hashrate */
extern const lv_font_t font_archivo_medium_17; /* Archivo Medium (wdth 88%), 17 px - insight sentence in 14-hashrate */
extern const lv_font_t font_archivo_bold_20; /* Archivo Bold (wdth 100%), 20 px - 14-hashrate screen title */
extern const lv_font_t font_archivo_bold_24; /* Archivo Bold (wdth 100%), 24 px - average values in 14-hashrate (digits only) */

#ifdef __cplusplus
}
#endif

#endif /* NQPP_DISPLAYS_FONTS_H */
