#pragma once

#include "lvgl.h"

// autogenerated, do not modify!

class Theme {
  protected:
    // Default-initialized to nullptr so that on profiles which strip the
    // ThemeXxx subclass constructor bodies (see below), a freshly
    // constructed Theme/ThemeXxx never holds a dangling/garbage pointer:
    // callers must null-check the getters instead of assuming a valid image.
    const lv_img_dsc_t *ui_img_initscreen2 = nullptr;
    const lv_img_dsc_t *ui_img_miningscreen2 = nullptr;
    const lv_img_dsc_t *ui_img_portalscreen = nullptr;
    const lv_img_dsc_t *ui_img_btcscreen = nullptr;
    const lv_img_dsc_t *ui_img_settingsscreen = nullptr;
    const lv_img_dsc_t *ui_img_splashscreen2 = nullptr;
    const lv_img_dsc_t *ui_img_globalStats = nullptr;

  public:
    // Getters
    const lv_img_dsc_t *getInitscreen2() const {
        return ui_img_initscreen2;
    }
    const lv_img_dsc_t *getMiningscreen2() const {
        return ui_img_miningscreen2;
    }
    const lv_img_dsc_t *getPortalscreen() const {
        return ui_img_portalscreen;
    }
    const lv_img_dsc_t *getBtcscreen() const {
        return ui_img_btcscreen;
    }
    const lv_img_dsc_t *getSettingsscreen() const {
        return ui_img_settingsscreen;
    }
    const lv_img_dsc_t *getSplashscreen2() const {
        return ui_img_splashscreen2;
    }
    const lv_img_dsc_t *getGlobalstats() const {
        return ui_img_globalStats;
    }

    // Setters
    void setInitscreen2(const lv_img_dsc_t *img) {
        ui_img_initscreen2 = img;
    }
    void setMiningscreen2(const lv_img_dsc_t *img) {
        ui_img_miningscreen2 = img;
    }
    void setPortalscreen(const lv_img_dsc_t *img) {
        ui_img_portalscreen = img;
    }
    void setBtcscreen(const lv_img_dsc_t *img) {
        ui_img_btcscreen = img;
    }
    void setSettingsscreen(const lv_img_dsc_t *img) {
        ui_img_settingsscreen = img;
    }
    void setSplashscreen2(const lv_img_dsc_t *img) {
        ui_img_splashscreen2 = img;
    }
    void setGlobalstats(const lv_img_dsc_t *img) {
        ui_img_globalStats = img;
    }
};

// image files for theme NerdOctaxeGamma
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdOctaxeGamma_globalStats_png);

// image files for theme NerdQaxePlus
LV_IMG_DECLARE(ui_img_NerdQaxePlus_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus_globalStats_png);

// image files for theme NerdAxe
LV_IMG_DECLARE(ui_img_NerdAxe_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdAxe_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdAxe_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdAxe_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdAxe_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdAxe_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdAxe_globalStats_png);

// image files for theme NerdOctaxePlus
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdOctaxePlus_globalStats_png);

// image files for theme NerdEko
LV_IMG_DECLARE(ui_img_NerdEko_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdEko_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdEko_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdEko_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdEko_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdEko_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdEko_globalStats_png);

// image files for theme NerdHaxeGamma
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdHaxeGamma_globalStats_png);

// image files for theme NerdAxeGamma
LV_IMG_DECLARE(ui_img_NerdAxeGamma_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdAxeGamma_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdAxeGamma_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdAxeGamma_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdAxeGamma_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdAxeGamma_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdAxeGamma_globalStats_png);

// image files for theme NerdQaxePlus2
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_globalStats_png);

// image files for theme NerdQX
LV_IMG_DECLARE(ui_img_NerdQX_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQX_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQX_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdQX_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdQX_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdQX_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQX_globalStats_png);


// class  for theme NerdOctaxeGamma
class ThemeNerdoctaxegamma : public Theme {
public:
    ThemeNerdoctaxegamma() {
        // Body compiled out on the 480x320 profile: nothing there uses Theme
        // images, so keeping this empty lets themes.c (and its ~1.14 MB of
        // PNG data) be dropped from SRCS entirely on that profile (see
        // main/CMakeLists.txt). Theme's members default to nullptr, so
        // getters return nullptr and callers must null-check.
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdOctaxeGamma_initscreen2_png);
        setMiningscreen2(&ui_img_NerdOctaxeGamma_miningscreen2_png);
        setPortalscreen(&ui_img_NerdOctaxeGamma_portalscreen_png);
        setBtcscreen(&ui_img_NerdOctaxeGamma_btcscreen_png);
        setSettingsscreen(&ui_img_NerdOctaxeGamma_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdOctaxeGamma_splashscreen2_png);
        setGlobalstats(&ui_img_NerdOctaxeGamma_globalStats_png);
#endif
    }
};

// class  for theme NerdQaxePlus
class ThemeNerdqaxeplus : public Theme {
public:
    ThemeNerdqaxeplus() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdQaxePlus_initscreen2_png);
        setMiningscreen2(&ui_img_NerdQaxePlus_miningscreen2_png);
        setPortalscreen(&ui_img_NerdQaxePlus_portalscreen_png);
        setBtcscreen(&ui_img_NerdQaxePlus_btcscreen_png);
        setSettingsscreen(&ui_img_NerdQaxePlus_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdQaxePlus_splashscreen2_png);
        setGlobalstats(&ui_img_NerdQaxePlus_globalStats_png);
#endif
    }
};

// class  for theme NerdAxe
class ThemeNerdaxe : public Theme {
public:
    ThemeNerdaxe() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdAxe_initscreen2_png);
        setMiningscreen2(&ui_img_NerdAxe_miningscreen2_png);
        setPortalscreen(&ui_img_NerdAxe_portalscreen_png);
        setBtcscreen(&ui_img_NerdAxe_btcscreen_png);
        setSettingsscreen(&ui_img_NerdAxe_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdAxe_splashscreen2_png);
        setGlobalstats(&ui_img_NerdAxe_globalStats_png);
#endif
    }
};

// class  for theme NerdOctaxePlus
class ThemeNerdoctaxeplus : public Theme {
public:
    ThemeNerdoctaxeplus() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdOctaxePlus_initscreen2_png);
        setMiningscreen2(&ui_img_NerdOctaxePlus_miningscreen2_png);
        setPortalscreen(&ui_img_NerdOctaxePlus_portalscreen_png);
        setBtcscreen(&ui_img_NerdOctaxePlus_btcscreen_png);
        setSettingsscreen(&ui_img_NerdOctaxePlus_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdOctaxePlus_splashscreen2_png);
        setGlobalstats(&ui_img_NerdOctaxePlus_globalStats_png);
#endif
    }
};

// class  for theme NerdEko
class ThemeNerdeko : public Theme {
public:
    ThemeNerdeko() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdEko_initscreen2_png);
        setMiningscreen2(&ui_img_NerdEko_miningscreen2_png);
        setPortalscreen(&ui_img_NerdEko_portalscreen_png);
        setBtcscreen(&ui_img_NerdEko_btcscreen_png);
        setSettingsscreen(&ui_img_NerdEko_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdEko_splashscreen2_png);
        setGlobalstats(&ui_img_NerdEko_globalStats_png);
#endif
    }
};

// class  for theme NerdHaxeGamma
class ThemeNerdhaxegamma : public Theme {
public:
    ThemeNerdhaxegamma() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdHaxeGamma_initscreen2_png);
        setMiningscreen2(&ui_img_NerdHaxeGamma_miningscreen2_png);
        setPortalscreen(&ui_img_NerdHaxeGamma_portalscreen_png);
        setBtcscreen(&ui_img_NerdHaxeGamma_btcscreen_png);
        setSettingsscreen(&ui_img_NerdHaxeGamma_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdHaxeGamma_splashscreen2_png);
        setGlobalstats(&ui_img_NerdHaxeGamma_globalStats_png);
#endif
    }
};

// class  for theme NerdAxeGamma
class ThemeNerdaxegamma : public Theme {
public:
    ThemeNerdaxegamma() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdAxeGamma_initscreen2_png);
        setMiningscreen2(&ui_img_NerdAxeGamma_miningscreen2_png);
        setPortalscreen(&ui_img_NerdAxeGamma_portalscreen_png);
        setBtcscreen(&ui_img_NerdAxeGamma_btcscreen_png);
        setSettingsscreen(&ui_img_NerdAxeGamma_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdAxeGamma_splashscreen2_png);
        setGlobalstats(&ui_img_NerdAxeGamma_globalStats_png);
#endif
    }
};

// class  for theme NerdQaxePlus2
class ThemeNerdqaxeplus2 : public Theme {
public:
    ThemeNerdqaxeplus2() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdQaxePlus2_initscreen2_png);
        setMiningscreen2(&ui_img_NerdQaxePlus2_miningscreen2_png);
        setPortalscreen(&ui_img_NerdQaxePlus2_portalscreen_png);
        setBtcscreen(&ui_img_NerdQaxePlus2_btcscreen_png);
        setSettingsscreen(&ui_img_NerdQaxePlus2_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdQaxePlus2_splashscreen2_png);
        setGlobalstats(&ui_img_NerdQaxePlus2_globalStats_png);
#endif
    }
};

// class  for theme NerdQX
class ThemeNerdqx : public Theme {
public:
    ThemeNerdqx() {
#ifndef DISPLAY_PROFILE_YYSLUPING_480X320
        setInitscreen2(&ui_img_NerdQX_initscreen2_png);
        setMiningscreen2(&ui_img_NerdQX_miningscreen2_png);
        setPortalscreen(&ui_img_NerdQX_portalscreen_png);
        setBtcscreen(&ui_img_NerdQX_btcscreen_png);
        setSettingsscreen(&ui_img_NerdQX_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdQX_splashscreen2_png);
        setGlobalstats(&ui_img_NerdQX_globalStats_png);
#endif
    }
};

